-- Player Claim Tokens
-- This migration adds a player_claim_tokens table and supporting functions
-- for coaches to generate claim links that players use to link their profile

-- ============================================
-- TABLE
-- ============================================

CREATE TABLE player_claim_tokens (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    token TEXT UNIQUE NOT NULL,
    player_id UUID NOT NULL REFERENCES players(id) ON DELETE CASCADE,
    team_id UUID NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
    created_by UUID NOT NULL REFERENCES profiles(id),
    expires_at TIMESTAMPTZ NOT NULL,
    claimed_at TIMESTAMPTZ,
    claimed_by UUID REFERENCES profiles(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE player_claim_tokens IS 'Tokens generated by coaches for players to claim their profile';
COMMENT ON COLUMN player_claim_tokens.token IS 'Random 32-char hex string used in the claim URL';
COMMENT ON COLUMN player_claim_tokens.expires_at IS 'Token expiry, default 7 days from creation';
COMMENT ON COLUMN player_claim_tokens.claimed_at IS 'NULL until a player claims the token';
COMMENT ON COLUMN player_claim_tokens.claimed_by IS 'Profile ID of the user who claimed the token';

-- ============================================
-- INDEXES
-- ============================================

CREATE INDEX idx_claim_tokens_token ON player_claim_tokens(token);
CREATE INDEX idx_claim_tokens_player ON player_claim_tokens(player_id);
CREATE INDEX idx_claim_tokens_team ON player_claim_tokens(team_id);

-- ============================================
-- TOKEN GENERATION FUNCTION
-- ============================================

-- Generates a cryptographically secure 32-char hex token
CREATE OR REPLACE FUNCTION generate_claim_token()
RETURNS TEXT AS $$
BEGIN
    RETURN encode(gen_random_bytes(16), 'hex');
END;
$$ LANGUAGE plpgsql;

-- ============================================
-- CLAIM PLAYER FUNCTION
-- ============================================

-- Atomically validates a token, links the player to the current user,
-- and marks the token as claimed. Returns player_id and team_id on success.
CREATE OR REPLACE FUNCTION claim_player(p_token TEXT)
RETURNS TABLE(player_id UUID, team_id UUID) AS $$
DECLARE
    v_token_row player_claim_tokens%ROWTYPE;
BEGIN
    -- Lock the token row to prevent concurrent claims
    SELECT * INTO v_token_row
    FROM player_claim_tokens pct
    WHERE pct.token = p_token
    FOR UPDATE;

    -- Validate token exists
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Invalid claim token' USING ERRCODE = 'P0001';
    END IF;

    -- Validate token has not expired
    IF v_token_row.expires_at < NOW() THEN
        RAISE EXCEPTION 'Claim token has expired' USING ERRCODE = 'P0002';
    END IF;

    -- Validate token has not already been claimed
    IF v_token_row.claimed_at IS NOT NULL THEN
        RAISE EXCEPTION 'Claim token has already been used' USING ERRCODE = 'P0003';
    END IF;

    -- Validate the player is not already linked to a user
    IF EXISTS (
        SELECT 1 FROM players p
        WHERE p.id = v_token_row.player_id
        AND p.user_id IS NOT NULL
    ) THEN
        RAISE EXCEPTION 'Player is already linked to a user account' USING ERRCODE = 'P0004';
    END IF;

    -- Mark the token as claimed
    UPDATE player_claim_tokens
    SET claimed_at = NOW(),
        claimed_by = auth.uid()
    WHERE id = v_token_row.id;

    -- Link the player to the current user
    UPDATE players
    SET user_id = auth.uid()
    WHERE id = v_token_row.player_id;

    -- Set user role to 'player' if not already set
    UPDATE profiles
    SET role = 'player',
        updated_at = NOW()
    WHERE id = auth.uid()
    AND (role IS NULL OR role = '');

    -- Return the player and team info
    RETURN QUERY SELECT v_token_row.player_id, v_token_row.team_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ============================================
-- ROW LEVEL SECURITY
-- ============================================

ALTER TABLE player_claim_tokens ENABLE ROW LEVEL SECURITY;

-- Inline coach check: avoids dependency on is_team_coach() which may not exist yet
-- Matches the same logic: coach_assignments row + profile role in (head_coach, assistant_coach)

-- Coaches can insert tokens for players on their teams
CREATE POLICY "Coaches can create claim tokens"
    ON player_claim_tokens FOR INSERT
    WITH CHECK (
        EXISTS (
            SELECT 1 FROM coach_assignments ca
            INNER JOIN profiles p ON p.id = ca.coach_id
            WHERE ca.team_id = player_claim_tokens.team_id
            AND ca.coach_id = auth.uid()
            AND p.role IN ('head_coach', 'assistant_coach')
        )
        AND EXISTS (
            SELECT 1 FROM team_memberships tm
            WHERE tm.player_id = player_claim_tokens.player_id
            AND tm.team_id = player_claim_tokens.team_id
            AND tm.is_active = true
        )
    );

-- Coaches can view tokens for their teams
CREATE POLICY "Coaches can view team claim tokens"
    ON player_claim_tokens FOR SELECT
    USING (
        EXISTS (
            SELECT 1 FROM coach_assignments ca
            INNER JOIN profiles p ON p.id = ca.coach_id
            WHERE ca.team_id = player_claim_tokens.team_id
            AND ca.coach_id = auth.uid()
            AND p.role IN ('head_coach', 'assistant_coach')
        )
    );

-- Authenticated users can look up a token by its value (for the claim page)
CREATE POLICY "Users can view token by value"
    ON player_claim_tokens FOR SELECT
    USING (auth.uid() IS NOT NULL);

-- Coaches can delete unclaimed tokens for their teams
CREATE POLICY "Coaches can delete unclaimed tokens"
    ON player_claim_tokens FOR DELETE
    USING (
        EXISTS (
            SELECT 1 FROM coach_assignments ca
            INNER JOIN profiles p ON p.id = ca.coach_id
            WHERE ca.team_id = player_claim_tokens.team_id
            AND ca.coach_id = auth.uid()
            AND p.role IN ('head_coach', 'assistant_coach')
        )
        AND claimed_at IS NULL
    );
